version: '3'

services:
  db:
    image: mariadb:10.6
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - /opt/nextcloud/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=RootPass
      - MYSQL_PASSWORD=NextPass
      - MYSQL_DATABASE=nextcloudtw
      - MYSQL_USER=nextcloudtw
    networks:
      - nextcloud_net

  app:
    image: nextcloud
    restart: unless-stopped
    ports:
      - "8081:80"  # Доступ к Nextcloud извне через порт 8081
    volumes:
      - /opt/nextcloud/apache:/var/www/html
    environment:
      - MYSQL_PASSWORD=NextPass
      - MYSQL_DATABASE=nextcloudtw
      - MYSQL_USER=nextcloudtw
      - MYSQL_HOST=db
    depends_on:
      - db
    networks:
      - nextcloud_net

networks:
  nextcloud_net:
    driver: bridge